Add fn strip-margin
tolitius/yang pull request #3
Opened 2021-09-01 15:58 UTC by danielmiladinov

Similar to [`String.stripMargin`](https://www.scala-lang.org/api/current/scala/collection/StringOps.html#stripMargin:String) extension method in Scala; e.g.:
```clojure
(require '[yang.lang :as yl])
=> nil

(println
  (yl/strip-margin "|<?xml version='1.0' encoding='utf-8'?>
                    |<people>
                    |  <person>
                    |    <name>Joe Smith</name>
                    |  </person>
                    |</people>"))
<?xml version='1.0' encoding='utf-8'?>
<people>
  <person>
    <name>Joe Smith</name>
  </person>
</people>
=> nil
```

Signed-off-by: Daniel Miladinov <daniel.miladinov@gmail.com>

2021-09-03 00:14 UTC, tolitius requested changes
thanks for the PR!

2021-09-03 00:14 UTC, tolitius commented on src/yang/lang.clj
> +  ([string] (strip-margin string "\\|")))
flip the arity:

```clojure
(defn strip-margin
 ([string]
  (strip-margin string "\\|"))
 ([string delimiter] (->> string
                      s/split-lines
                      (map s/triml)
                      (map #(.replaceFirst % delimiter ""))
                      (s/join "\n"))))
```

2021-09-03 13:26 UTC, danielmiladinov commented on src/yang/lang.clj
> +  ([string] (strip-margin string "\\|")))
Done!

2021-09-08 03:07 UTC, tolitius commented
thank you!

2021-09-08 03:07 UTC, merged